### PR TITLE
Install accessibility add on in Storybook

### LINKED ISSUE #171: Add a11y-addon to storybook
Follow the instructions at [Storybook - set up ally addon](https://storybook.js.org/docs/react/writing-tests/accessibility-testing#accessibility-checks-with-a11y-addon) in order to install and configure the accessibility add on. (Only this section needs to be followed, no need to add anything in the configure section)

Please use yarn to install the new package and follow the Typescript instructions for configuration.

### PR DESCRIPTION
**Pull request by YuriDevAT**
## Describe your changes
I installed the accessibility extension for storybook ts following the instruction on storybook which were provided in the issue.

## Screenshots - If Any (Optional)

**Storybook run with yarn storybook in browser**

**before**

Storybook add on bar showing three addons, controls, actions, interactions.

**after**
Storybook add on bar showing four addons, controls, actions, interactions, accessibility.

`.storybook/main.js file`

**before**

5 add ons listed in the config file

**after**
6 add ons listed in the config file, included the latest accessibility add on

## Link to issue

Closes #171

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/181"></a>

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
We're there no changes to the yarn.lock file when you added the extension?

**Comment by YuriDevAT** [comment]
My bad. Yes, there were changes, but I wasn't sure if this is something which gets pushed as well 😞 . I will push the file immediately.

**Comment by EmmaDawsonDev** [comment]
No worries! Sometimes it sneaks in there when it shouldn't so it's hard to know when to add it or not. My general rule of thumb is if you've installed a new package with npm/yarn then the lock file should be committed, otherwise you can ignore it.

**Review by EmmaDawsonDev — APPROVED** [review]
Look great! Thanks for contributing :D

**Comment by YuriDevAT** [comment]
I see. Thanks for clarification 😄 .

Thank you so much for letting me contribute 👍🏽

**Comment by EmmaDawsonDev** [comment]
You're always welcome to contribute when you have time 😄

**Pull request merged**
