### PR TITLE
[issue168] create storybook skeleton of NavItem

### LINKED ISSUE #168: Add NavItem story
The NavItem component already exists but there's no story for it in storybook.

In the stories folder add a file named NavItem.stories.tsx

Using the Header.stories.tsx file as a template, adapt the contents of that file for the NavItem component.

The NavItem component takes the following props:
```
interface NavItemProps {
	page: IPage
	activeNavLink: string
	handleNavClick?: () => void
}
```

Use the command yarn storybook to run the story on localhost and check that component is visible in storybook.

### PR DESCRIPTION
**Pull request by Huluvu424242**
Signed-off-by: huluvu424242 <huluvu424242@gmail.com>

## Describe your changes
add an skeleton for the storybook entry of NavItem

## Screenshots - If Any (Optional)
Example page
image

Example page with lighthouse test
image

## Link to issue

Closes #168 

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [no] I ran the app and tested it locally to verify that it works as expected.
- [98%] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)

I need an hint. This codes is not valid in my mind but i dont have an idea for an page (IPage). 
Additionally the lighthouse report meets only 98% for a11y. But this is the second problem. 

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/169"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — APPROVED** [review]
Thanks @Huluvu424242 It looks like you’ve done it right to me. I can take a look at why some of the styling is not being applied later (I was having trouble with the css config when I installed storybook so I probably did something wrong). I imagine the lighthouse score is coming from an accessibility error with the storybook layout and not the component itself as I’ve checked the component before as part of the website and it passes.

**Comment by Huluvu424242** [comment]
> Thanks @Huluvu424242 It looks like you’ve done it right to me. I can take a look at why some of the styling is not being applied later (I was having trouble with the css config when I installed storybook so I probably did something wrong). I imagine the lighthouse score is coming from an accessibility error with the storybook layout and not the component itself as I’ve checked the component before as part of the website and it passes.

Thanks for merging

(Only for information, i have my 4 PRs complete - i am working on this project because it is interesting to me.)

**Comment by EmmaDawsonDev** [comment]
You’re more than welcome to continue contributing :D

**Comment by EmmaDawsonDev** [comment]
I had a quick look at the styling and turns out I had added list-style: none to the wrong component so this PR was exactly right and it helped to spot an error in the CSS (which I've now fixed)

**Pull request merged**
