### PR TITLE
Feat/breadcrumbs info

### PR DESCRIPTION
**Pull request by EmmaDawsonDev**
## Describe your changes
Added a page for breadcrumbs and made small tweaks to a few other pages CSS

## Link to issue

Closes #

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [x] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by ctoffanin — APPROVED** [review]
Awesome work, Emma!

**Comment by EmmaDawsonDev** [comment]
@ctoffanin Aww I'm so happy you're still here 😄

**Comment by ctoffanin** [comment]
@EmmaDawsonDev of course I am! I have less time but I'm here! ❤️

**Comment by EmmaDawsonDev** [comment]
@ctoffanin Same! Time is not easy to come by. Today I'm taking advantage of the Easter bank holiday. And I just bought a real domain name for the project as some motivation 😄 Once the SSL cert goes through then https://accessibleweb.dev will be live 🥳

**Comment by ctoffanin** [comment]
@EmmaDawsonDev that's so cool! Nice!

**Pull request merged**
