### PR TITLE
8 Tasks done to add h1 tag in pages

### LINKED ISSUE #315: Move h1 from layout into each page
- [ ] Remove the h1 from the Layout component
- [ ] Remove the headerTitle prop from the interface and props in the Layout component
- [ ] Remove the h1 styles from the Layout styles file
- [ ] Add a h1 to the index page before the first section. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a h1 to the [content] page before as the first element inside the fragment. Remove the headerTitle prop from Layout and add the text directly into the h1
- [ ] Add a h1 to the about page before the first section. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a h1 to the 404 page before the first div. Remove the headerTitle prop from Layout and add the text directly into the h1.
- [ ] Add a font-size for the h1 into the global styles file. Set it to 2.5 rem.

### PR DESCRIPTION
**Pull request by jgyfutub**
## Describe your changes
I have removed headerTitle props from .tsx code of these pages p and manually put <h1> tag for headings. Below is the screenshots for work done.Please inform in case of any problem occurs.
## Screenshots - If Any (Optional)
 \

About - Accessible Web Dev and 2 more pages - Personal - Microsoft​ Edge 14-06-2023 17_57_35
About - Accessible Web Dev and 2 more pages - Personal - Microsoft​ Edge 14-06-2023 17_58_33
About - Accessible Web Dev and 2 more pages - Personal - Microsoft​ Edge 14-06-2023 17_58_44

## Link to issue

Closes #315 

## Checklist before requesting a review

- [yes] I have performed a self-review of my code.
- [yes] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [yes] I ran the app and tested it locally to verify that it works as expected.
- [no] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please revert the changes to things that aren't related to the h1 issue.

**Comment by EmmaDawsonDev** [comment]
Do you need some help with this @jgyfutub ?

**Comment by jgyfutub** [comment]
@EmmaDawsonDev I had removed all commits that were not related to h1 please review the changes

**Comment by EmmaDawsonDev** [comment]
Looks like you need to revert this commit `68baba645d476aa55c52c66896c31ffae7890388` in order to remove the changes to the yarn.lock file and the package.json file. Neither of these files should be included in this PR.

**Comment by jgyfutub** [comment]
ok I will try thanks for helping.

**Comment by jgyfutub** [comment]
I have removed the yarn.lock and package.json file by using git revert , please review the changes.

**Review by EmmaDawsonDev — APPROVED** [review]
Looks good! Thank you for persevering with this 😃

**Pull request merged**
