### PR TITLE
Fix missing space

### LINKED ISSUE #175: incorrect text formatting
**Describe the bug**
Missing space in footer text

**Screenshots**
chrome_rIHFcQoxLc

### PR DESCRIPTION
**Pull request by murtuzaalisurti**
## Describe your changes
Added `&nbsp;` to fix space issue

## Link to issue
Closes #175 

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/176"></a>

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
Could you please use `{" "}` instead as `&nbsp;` gets read out by some screen readers providing a sub-optimal experience.

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
See comment above.

**Comment by murtuzaalisurti** [comment]
> Could you please use `{" "}` instead as `&nbsp;` gets read out by some screen readers providing a sub-optimal experience.

Done ✔️

**Review by EmmaDawsonDev — APPROVED** [review]
Thanks for your help!

**Pull request merged**
