### PR TITLE
Remove default exports from components and add named exports

### LINKED ISSUE #230: Named exports
We have decided that all components will use named exports. However, at the moment some are still using export default.

Please go through the components (not pages) and update each to use named exports.

Example: 
```
const AlertsTemplate = () => {
	return <WorkInProgress />
}

export default AlertsTemplate
```

Should become:
```
export const AlertsTemplate = () => {
	return <WorkInProgress />
}

```

### PR DESCRIPTION
**Pull request by hariscs**
## Describe your changes
Removed default exports from components and added named exports
## Link to issue

Closes #230 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [x] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/242"></a>

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
Could you also make sure the corresponding imports in the pages/[content].tsx are updated so that nothing breaks?

**Comment by hariscs** [comment]
Yeah, @EmmaDawsonDev 
I'm working on that

**Comment by EmmaDawsonDev** [comment]
Brilliant! I thought you might be as this was still in draft but realised I forgot to mention it in the issue (and I myself missed it the other day when making a PR and then broke things 🙄 )

**Comment by hariscs** [comment]
No worries, happen sometime.
I'm testing everything before making a PR to make sure I don't break anything.

**Review by ctoffanin — APPROVED** [review]

**Pull request merged**
