### PR TITLE
Add capital I at the start of every interface

### LINKED ISSUE #232: All interfaces should start with capital I
Please go through the files and find any interfaces that don't begin with a capital I. 

Example:
```
export interface HeaderProps {
	headerTitle: string
	handleNavClick: () => void
	showNavMobile: boolean
}

export const Header = (props: HeaderProps) => {
```

Should be:
```
export interface IHeaderProps {
	headerTitle: string
	handleNavClick: () => void
	showNavMobile: boolean
}

export const Header = (props: IHeaderProps) => {
```

### PR DESCRIPTION
**Pull request by hariscs**
## Describe your changes
added I at the start of every interface

## Link to issue

Closes #232 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [x] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [x] I ran the app and tested it locally to verify that it works as expected.
- [x] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/241"></a>

### CODE REVIEW

**Comment by hariscs** [comment]
@EmmaDawsonDev why we are adding capital I at the start of every interface? is this some kind of convention?

**Review by ctoffanin — APPROVED** [review]

**Comment by ctoffanin** [comment]
Good job @hariscs, thank you!

**Comment by ctoffanin** [comment]
> @EmmaDawsonDev why we are adding capital I at the start of every interface? is this some kind of convention?

Yes, it's a convention. In this way, we can easily identify that the props are coming from an interface because it's prefixed with `I`.

**Comment by hariscs** [comment]
@ctoffanin thank you.

**Pull request merged**
