### PR TITLE
Fixed #365 i added scroll-margin-top:5rem to global.css file

### LINKED ISSUE #365: Need scroll margin or padding
**Describe the bug**
When a user uses the page navigation links to navigate to a section of the page the heading ends up hidden underneath the fixed header. If I remember correctly it is possible to add something like scroll-margin-top as a css property and set it to the height of the header (a css variable) in order to push the scroll position down and prevent the heading from being hidden.

**To Reproduce**
1. Go to navigation page
2. Click on one of the links in the page navigation accordion
3. Notice that section heading is not visible

**Expected behavior**
Section heading is visible below the header

### PR DESCRIPTION
**Pull request by 2div**
## Describe your changes

h2,
h3,
h4,
h5,
h6 {
	margin: 1rem 0 0 0;
	scroll-margin-top: 5rem; // i added this line to fix the issue
}

## Link to issue
Closes #365 

## Checklist before requesting a review

- [ Yes] I have performed a self-review of my code.
- [ Yes] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ Yes] I ran the app and tested it locally to verify that it works as expected.
- [ Yes] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
The scroll margin top works great. However, please revert the changes to the package-lock file and the yarn.lock file. As there were no changes made to these files they don't need to be included in the PR. As soon as they are reverted then this is ready to merge.

**Comment by 2div** [comment]
> The scroll margin top works great. However, please revert the changes to the package-lock file and the yarn.lock file. As there were no changes made to these files they don't need to be included in the PR. As soon as they are reverted then this is ready to merge.

Thank you for your feedback.  Can you please explain what you mean by revert the changes to the package-lock file and the yarn.lock file. I do not think i changed or edited these files. I only edit the global CSS file.

May i know what and how to revert these changes you mentioned so that we can do merg ?

**Comment by EmmaDawsonDev** [comment]
Sure. These files are created when you do npm install or yarn install. And then if you use the command `git add .` then it will add them to the commit even though you didn’t make changes to them. That’s why the contributing files suggest using `git add name-of-file` instead because it’s safer. But it’s no problem as almost everything with git can be undone. 

First go to your branch and in the terminal you want to type `git revert commit-hash` which in this case is `git revert 0a99424`. You should then be able to do ‘git add styles/globals.css’ and commit and push. That should automatically update this pull request

**Comment by 2div** [comment]
> Sure. These files are created when you do npm install or yarn install. And then if you use the command `git add .` then it will add them to the commit even though you didn’t make changes to them. That’s why the contributing files suggest using `git add name-of-file` instead because it’s safer. But it’s no problem as almost everything with git can be undone.
> 
> First go to your branch and in the terminal you want to type `git revert commit-hash` which in this case is `git revert 0a99424`. You should then be able to do ‘git add styles/globals.css’ and commit and push. That should automatically update this pull request

Thank you for your explanation this topic to me. I did not know about it but now i learned from you.
I did    git revert 0a99424`. then ‘git add styles/globals.css’

I request re-review but i am not sure if that the right thing because its my first time see change requested to PR 
Should i do new PR ? please advise me. Thank you

**Comment by EmmaDawsonDev** [comment]
Great, now the two extra files are gone. For some reason it didn't keep the change that you made to the styles file. If you can add the margin-scroll-top back in and then do `git add styles/globals.css` again and then commit and push it should be ready to merge. No need to do a new PR, everything you update in your branch will appear here as soon as you push it.

**Comment by 2div** [comment]
> Great, now the two extra files are gone. For some reason it didn't keep the change that you made to the styles file. If you can add the margin-scroll-top back in and then do `git add styles/globals.css` again and then commit and push it should be ready to merge. No need to do a new PR, everything you update in your branch will appear here as soon as you push it.

Ok , I followed the steps and pushed again. Than you

**Review by EmmaDawsonDev — APPROVED** [review]
Thanks so much for your help!

**Pull request merged**
