### PR TITLE
Fix margin top&bottom 14px

### PR DESCRIPTION
**Pull request by blyncnov**
## Link to issue
Issue #348

## Additional Information (Optional)
 The top and bottom margins are set to be 14 px each ...

### CODE REVIEW

**Comment by blyncnov** [comment]
All done

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Apologies if I was unclear in the issue. The margin needs to go on the `<li>` elements. Changing it here adds it to the `<ul>` element.

**Comment by blyncnov** [comment]
Alright.. changing that ?

**Review by blyncnov — COMMENTED** [review]
Please check again

**Review by EmmaDawsonDev — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
