### PR TITLE
added PULL REQUEST TEMPLATE

### LINKED ISSUE #42: Add a PR template
Link to the official [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

### PR DESCRIPTION
**Pull request by MrKrishnaAgarwal**
cc @EmmaDawsonDev 

closes #42

<a href="https://gitpod.io/#https://github.com/AccessibleForAll/AccessibleWebDev/pull/60"></a>

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Please add this in the .github folder alongside the issue template, thanks!

**Comment by MrKrishnaAgarwal** [comment]
> Please add this in the .github folder alongside the issue template, thanks!

Sure, I'll do that

**Comment by MrKrishnaAgarwal** [comment]
@EmmaDawsonDev

**Review by EmmaDawsonDev — APPROVED** [review]
thank you for your contribution!

**Comment by MrKrishnaAgarwal** [comment]
Thanks! 
Please create more issues to work upon.

**Comment by MrKrishnaAgarwal** [comment]
Yes :)
No worries \('_')/

**Pull request merged**
