### PR TITLE
feat: add content about audio

### LINKED ISSUE #358: Do page on Audio
**Is your feature request related to a problem? Please describe.**
I noticed that the [Audio page](https://accessibleweb.dev/audio) is not finished yet. 

**Describe the solution you'd like**
I'm doing 100 Days of Open Source, so I'd like to help create the content on this topic and use my PR as a highlight @EmmaDawsonDev. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by CBID2**
## Describe your changes
This PR is finishing the audio page. 
## Link to issue

Closes #358 

## Checklist before requesting a review

- [ ] I have performed a self-review of my code.
- [ ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [ ] I ran the app and tested it locally to verify that it works as expected.
- [ ] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Comment by penguin011** [comment]
👍

**Comment by EmmaDawsonDev** [comment]
Apologies for taking so long to get back to you on this. I got into a bit of an open source slump. What do you need me to do to help you with this to get it ready for review?

**Comment by CBID2** [comment]
> Apologies for taking so long to get back to you on this. I got into a bit of an open source slump. What do you need me to do to help you with this to get it ready for review?
Hey @EmmaDawsonDev. It's fine. I've been slow in my PR too. I think doing a pair programming session would help immensely. I'm really struggling with formatting the code.

**Comment by EmmaDawsonDev** [comment]
Sure, we can do that. Let's see if we can find a day/time that works for us both. What time zone are you in? I'm in Central European Summer Time (cest)

**Comment by CBID2** [comment]
> Sure, we can do that. Let's see if we can find a day/time that works for us both. What time zone are you in? I'm in Central European Summer Time (cest)

EST (U.S Eastern Standard Time). I'm free now :)

**Comment by EmmaDawsonDev** [comment]
Sorry I missed your message yesterday, I was just heading to bed. This week I can do that time today (Monday), Thursday or Sunday.

**Comment by EmmaDawsonDev** [comment]
Ok great, I think we can do it through discord but if not we can set up a Google meet

**Comment by CBID2** [comment]
> Ok great, I think we can do it through discord but if not we can set up a Google meet

Sure Discord is fine

**Comment by CBID2** [comment]
I made the commit @EmmaDawsonDev.  When you're awake, you can merge it! :)

**Review by EmmaDawsonDev — APPROVED** [review]
Thanks Chrissy!

**Review by penguin011 — COMMENTED** [review]
👍

**Pull request merged**
