### PR TITLE
Page last updated

### LINKED ISSUE #316: Move pageLastUpdated CSS to correct module
The styling for the `.pageLastUpdated` class should be moved from the globals.css file to the PageUpdated.module.css file

### PR DESCRIPTION
**Pull request by jgyfutub**
## Describe your changes
I have shifted PageLastUpdated class from global.css to PageLastUpdated.module.css. Please check the commits and review it
## Link to issue

Closes #316 

## Checklist before requesting a review

- [yes ] I have performed a self-review of my code.
- [yes ] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [yes ] I ran the app and tested it locally to verify that it works as expected.
- [ no] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Since these styles are no longer global, in order for the changes to be applied the styles need importing into the PageUpdated component. Then on line 5, where the styles are applied this `<p className="pageLastUpdated">` needs changing to this `<p className={styles.pageLastUpdated}>`

**Comment by jgyfutub** [comment]
okk,thanks for informing

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
This is almost ready for merging. There's just a missing import on the PageUpdated page.

Please add `import styles from "./PageUpdated.module.css"` to PageUpdated.tsx for the styles to be applied.

**Comment by jgyfutub** [comment]
thanks for informing,I have done the changes please review it

**Review by EmmaDawsonDev — APPROVED** [review]
Great, thank you!

**Pull request merged**
