### PR TITLE
fixed theme toggle

### LINKED ISSUE #290: Theme picker doesn’t toggle closed.
The theme picker button should toggle the pop up open and closed. This works with keyboard but with mouse it triggers it to open on every click. It should instead close the pop up if it’s already opened.

### PR DESCRIPTION
**Pull request by thehashmap**
## Describe your changes

This Pull request fixes the Theme Picker Toggle.

## Link to issue

Closes #290

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.
- [X] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Comment by EmmaDawsonDev** [comment]
Thanks for your PR, I will review it when I get some time this weekend.

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Thanks for taking a look at this however, I don't think the handleClickOutside function is the correct one to be modifying. 

I wonder if the handleThemeSwitcher is somehow triggering twice when someone clicks, since it works as expected with the keyboard, but this will need invetigating.

**Comment by thehashmap** [comment]
> Thanks for taking a look at this however, I don't think the handleClickOutside function is the correct one to be modifying.
> 
> I wonder if the handleThemeSwitcher is somehow triggering twice when someone clicks, since it works as expected with the keyboard, but this will need investigating.

Thanks for the review!

At first, I tried to check if handleThemeSwitcher is somehow triggering twice when someone clicks.

Then I checked if the issue was due to some other function and found out that on clicking the Theme button, the useOnClickOutside custom hook was not detecting the button.

So, I updated the code to also check if the click was on the button.

**Comment by thehashmap** [comment]
Now, Instead of adding the check in the handleClickOutside function, I have directly updated useOnClickOutside.

**Comment by EmmaDawsonDev** [comment]
Was neither event firing when the button was clicked or was the useOnClickOutside triggering but then the button click triggering and opening the pop up again?

**Comment by thehashmap** [comment]
The useOnClickOutside was triggering but then the button click was triggering it again and opening the pop up.

**Comment by EmmaDawsonDev** [comment]
Ok, that's good to know. I don't think passing a button ref to the custom hook is the right way to solve this issue since the hook should be as reusable as possible and passing the button ref makes it more tightly coupled and dependent on a button to trigger the opening of something. I do however think that the logic inside the hook might be flawed in some way. I don't know exactly but the mouseup and mousedown logic makes me wonder if there's something weird going on there.

At work we use a very similar hook that we've never had problems with so far. I wonder if it's worth switching for this one and see if it fixes the issue
```
import { RefObject, useEffect } from 'react';

type AnyEvent = MouseEvent | TouchEvent;

/**
 * React hook for listening for clicks outside of a specified element (see useRef).
 * This can be useful for closing a modal, a dropdown menu etc.
 * @see https://usehooks-ts.com/react-hook/use-on-click-outside
 */
export const useOnClickOutside = <T extends HTMLElement = HTMLElement>(
  ref: RefObject<T>,
  handler: (event: AnyEvent) => void
): void => {
  useEffect(() => {
    const listener = (event: AnyEvent) => {
      const el = ref?.current;

      if (!el || el.contains(event.target as Node)) {
        return;
      }

      handler(event);
    };

    document.addEventListener('mousedown', listener);
    document.addEventListener('touchstart', listener);

    return () => {
      document.removeEventListener('mousedown', listener);
      document.removeEventListener('touchstart', listener);
    };
  }, [ref, handler]);
};

export default useOnClickOutside;
```

**Comment by thehashmap** [comment]
The hook that you provided above did not solve the issue.

And I agree with you on what you said about the reusability of the code.
> I don't think passing a button ref to the custom hook is the right way to solve this issue since the hook should be as reusable as possible and passing the button ref makes it more tightly coupled and dependent on a button to trigger the opening of something.

So, shall I revert to my previous commit which solved the issue? There instead of updating the hook directly, I made the check in the handleClickOutside function to counter the flaw in the hook.

**Comment by EmmaDawsonDev** [comment]
I think I’ve got an idea and it’s actually to move the ref. The useOnClickOutside event will be triggered by clicking any child element within the ref so if we wrap the entire toggle in a div, put the ref on that instead of the ul then it encapsulates both the button and the list and should prevent the current behaviour because the button would be inside.

**Comment by thehashmap** [comment]
Thanks for the idea! 
This works. Let me update the PR.

**Comment by EmmaDawsonDev** [comment]
Fantastic! Thanks so much for your help! I’m actually on vacation right now with only my phone so I will wait until I’m home next week to merge it, so please leave it open and I’ll do it as soon as I’m back at my laptop.

**Review by EmmaDawsonDev — APPROVED** [review]
This works great now, thanks for your help in debugging the problem!

**Pull request merged**
