### PR TITLE
Code block responsive

### LINKED ISSUE #282: Code snippets are not responsive
## Is your feature request related to a problem? Please describe.**
The Code snippet block is not responsive for mobile devices , *overflow should not be blocked* in "CSS" to show how its should look in desktop view in code editors.

## To Reproduce
In Mobile devices :
1. Go to 'Headings Section from Side navbar'
2. Click on 'Headings'
3. Scroll down to 'Code snippet to show nesting of different headings'

## Describe the solution you'd like
The snippet should show **how to nest heading sections within one another in sequential order.**
It would be good if the blocks give same code view as the desktop view . It would be **more clear to see and easy to read.**

### In **Heading section**
accessibleweb dev_headings

### PR DESCRIPTION
**Pull request by Neha**
## Describe your changes

1. CSS changes
2. Component code change 

to make the code block responsive

## Screenshots - If Any (Optional)
Mobile view: 
Screenshot 2023-05-08 at 3 44 35 PM

Desktop View
Screenshot 2023-05-08 at 3 44 52 PM

## Link to issue

Closes #282 

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] Followed the repository's [Contributing Guidelines](/CONTRIBUTING.md).
- [X] I ran the app and tested it locally to verify that it works as expected.
- [X] I have checked my code with an automatic accessibility tool such as Axe Dev Tools or Wave 
      and it shows no errors.
## Additional Information (Optional)
Any additional information that you want to give us.

### CODE REVIEW

**Comment by Neha** [comment]
> Hello @Neha, thanks for raising a pull request in this project. The maintainers of this project are volunteers so please be understanding if it takes time before you get a response. We still appreciate your help with creating pull requests!

Hello @EmmaDawsonDev I have addressed all the comments. Thanks

**Review by EmmaDawsonDev — CHANGES_REQUESTED** [review]
Hi Neha!

I'm finally back from vacation so I can check this PR. It's well on the way to being ready to merge, there's just a few things I noticed when I was testing it:

- The media queries need adjusting. It works great at the breakpoints you've specified but for the ones you haven't it becomes unresponsive at certain sizes. I noticed problems between 668px - 799px and 1025px - 1264px.
- When the code blocks have scroll bars, they should be reachable by keyboard. Otherwise keyboard users can't scroll to read all of the content.
- Switch em values to rem values. That way they will always be consistent across the site, irrespective of font size.
- Remove any remaining !important in the CSS.

Let me know if you need any help with any of it.

**Comment by Neha** [comment]
> * 668px - 799p

Thank you @EmmaDawsonDev 

Is there a list of breakpoints we need to follow? Is yes, could you please share? 

I would prefer to keep mobile first and keep the breakpoints only for the tablets, and desktops.

**Comment by EmmaDawsonDev** [comment]
> > * 668px - 799p
> 
> Thank you @EmmaDawsonDev
> 
> Is there a list of breakpoints we need to follow? Is yes, could you please share?
> 
> I would prefer to keep mobile first and keep the breakpoints only for the tablets, and desktops.

I tend not to go by specific break points, but add them in only when I see something breaks. I think the only major one to be aware of is that the navigation, which flips from mobile navigation to desktop layout at 800px and over.

**Comment by Neha** [comment]
> > > * 668px - 799p
> > 
> > 
> > Thank you @EmmaDawsonDev
> > Is there a list of breakpoints we need to follow? Is yes, could you please share?
> > I would prefer to keep mobile first and keep the breakpoints only for the tablets, and desktops.
> 
> I tend not to go by specific break points, but add them in only when I see something breaks. I think the only major one to be aware of is that the navigation, which flips from mobile navigation to desktop layout at 800px and over.

Changes done. Please check. Thanks

**Comment by EmmaDawsonDev** [comment]
Hi Neha,

I'm still seeing that it breaks on certain screen sizes. I had a bit of a play around with some of the CSS you'd added. Try this and see if that helps:
```
.CodeBlockContainer {
	position: relative;
	width: 90vw;
	max-width: calc(1200px - 15rem);
}

.CodeBlock {
	overflow-x: auto;
}

@media only screen and (min-width: 800px) {
	.CodeBlockContainer {
		width: 65vw;
	}
}
```

**Comment by Neha** [comment]
> Hi Neha,
> 
> I'm still seeing that it breaks on certain screen sizes. I had a bit of a play around with some of the CSS you'd added. Try this and see if that helps:
> 
> ```
> .CodeBlockContainer {
> 	position: relative;
> 	width: 90vw;
> 	max-width: calc(1200px - 15rem);
> }
> 
> .CodeBlock {
> 	overflow-x: auto;
> }
> 
> @media only screen and (min-width: 800px) {
> 	.CodeBlockContainer {
> 		width: 65vw;
> 	}
> }
> ```

oh no!! Apologies. I had recorded a demo of all the breakpoints I tested and it was working fine ( I am not able to upload the recording here due to a size issue). However, I will just go ahead and implement the solution you suggested. 
Thanks :)

**Comment by Neha** [comment]
fixed. please check

**Review by EmmaDawsonDev — APPROVED** [review]
Thank you so much for your help with this Neha! It was not an easy problem to work on.

**Pull request merged**
